### ISSUE TITLE
scaffold project dotfiles fails every time

### ISSUE THREAD

**Issue by rajzik** [beemojs/beemo#75]
`npx nimbus scaffold project dotfiles`

Console output:
```
npx nimbus scaffold project dotfiles --debug
  beemo:reporter-loader Sorting by priority +0ms
  beemo:reporter-loader Bootstrapping with tool environment +0ms
  beemo:driver-loader Locating driver module babel +0ms
  beemo:driver-loader Resolving in order: @beemo/driver-babel, beemo-driver-babel +0ms
  beemo:driver-loader Found with module @beemo/driver-babel +137ms
  beemo:driver-loader Locating driver module eslint +0ms
  beemo:driver-loader Resolving in order: @beemo/driver-eslint, beemo-driver-eslint +0ms
  beemo:driver-loader Found with module @beemo/driver-eslint +45ms
  beemo:driver-loader Locating driver module jest +0ms
  beemo:driver-loader Resolving in order: @beemo/driver-jest, beemo-driver-jest +0ms
  beemo:driver-loader Found with module @beemo/driver-jest +44ms
  beemo:driver-loader Locating driver module prettier +0ms
  beemo:driver-loader Resolving in order: @beemo/driver-prettier, beemo-driver-prettier +0ms
  beemo:driver-loader Found with module @beemo/driver-prettier +51ms
  beemo:driver-loader Locating driver module typescript +1ms
  beemo:driver-loader Resolving in order: @beemo/driver-typescript, beemo-driver-typescript +0ms
  beemo:driver-loader Found with module @beemo/driver-typescript +78ms
  beemo:driver-loader Locating driver module webpack +0ms
  beemo:driver-loader Resolving in order: @beemo/driver-webpack, beemo-driver-webpack +0ms
  beemo:driver-loader Found with module @beemo/driver-webpack +42ms
  beemo:driver-loader Sorting by priority +0ms
  beemo:driver-loader Bootstrapping with tool environment +0ms
  beemo:script-loader Sorting by priority +0ms
  beemo:script-loader Bootstrapping with tool environment +0ms
  beemo:reporter-loader Using default boost reporter +505ms
  beemo:core Bootstrapping configuration module +0ms
  beemo:core Executing bootstrap function: Found +451ms
  beemo:core Locating configuration module root +16ms
  beemo:core Found configuration module root path: /mnt/c/git/asdf/node_modules/@airbnb/nimbus/lib/index.js +8ms
  beemo:core Running scaffold command +2ms
  beemo:core Instantiating pipeline +0ms
  beemo:routine:scaffold Bootstrapping routine +0ms
  beemo:core Running pipeline +1ms
  beemo:console Starting console render loop +0ms
  beemo:console Wrapping `stderr` stream +0ms
  beemo:console Wrapping `stdout` stream +0ms
  beemo:serial-executor Instantiating task executor +0ms
  beemo:serial-executor Serializing 1 tasks +0ms
  beemo:serial-executor Instantiating task executor +0ms
  beemo:serial-executor Serializing 1 tasks +0ms
  beemo:console Stopping console with an error +70ms
  beemo:console Rendering final console output +0ms
[1/1] SCAFFOLD Generating from templates (failed)

Loaded templates: node_modules/@airbnb/nimbus/lib/index.js/templates

Failed to find scaffolding templates "project/dotfiles/*.ejs" in configuration module.
    at ScaffoldRoutine.runGenerator (/mnt/c/git/asdf/node_modules/@beemo/core/lib/routines/ScaffoldRoutine.js:74:23)

  beemo:console Unwrapping `stderr` stream +1ms
  beemo:console Unwrapping `stdout` stream +1ms
```

It does look like it's looking in wrong folder.
` node_modules/@airbnb/nimbus/lib/index.js/templates` which doesn't make sense.

**Comment by milesj** [comment]
This is fixed in the latest version.

**Comment by rajzik** [comment]
@milesj thanks you are the best.

**Comment by pengchongfu** [comment]
Hi @milesj , it still failed as `moduleRoot ` is `node_modules/@airbnb/nimbus/lib/index.js` and this [fix](https://github.com/beemojs/beemo/commit/f9d0229476ad12194f52c33d7f95d78a45f2d898) doesn't work.

it seems caused by this [commit](https://github.com/beemojs/beemo/commit/195fbdcd450e4f69c0e2d62d1e93aa16d14a2907), `require.resolve(module)` return the `main` attribute in the `package.json`.

**Comment by milesj** [comment]
Another attempt here: https://github.com/beemojs/beemo/pull/78 It's kind of tricky.

**Comment by pengchongfu** [comment]
It works, Thanks 😊
